version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - bencodezen
  labels:
  - dependencies
  ignore:
  - dependency-name: workbox-build
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@vue/babel-preset-app"
    versions:
    - 4.5.11
  - dependency-name: all-contributors-cli
    versions:
    - 6.19.0
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 2.34.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
